### ISSUE TITLE
Pushes are not processed

### ISSUE THREAD

**Issue by matteocrippa** [Orion98MC/node_apns#3]
Hi Thierry,

I noticed an issue with new 0.0.4 version, I'm trying to send a push (I also tried sending more then once using forEach loop) but once started the scripts nothing happens.

I logged both the notification and notifier and all seems ok, but once I trigger notify() nothing happens, the callback function is never called so I not receive error or ok message.

I tried also using your snippet but I'm still falling back in the same issue.

I tried also setting verbose to true, but no messages were sent and notifier.elogs are empty.

**Comment by Orion98MC** [comment]
Hello Matteo,

Please show me some code to help me figure out the problem.

**Comment by matteocrippa** [comment]
The code is exactly the one you suggested in the read.me, except for the certificates (i keep them separted as v.0.0.3 and previous) and for the token id:

``` javascript
var 
 notifier = require('node_apns').services.Notifier(
    { 
         cert: require('fs').readFileSync(__dirname+'/certificates/prod_cert.pem'),
         key: require('fs').readFileSync(__dirname+'/certificates/prod_key.pem') 
    }, false)


/* 
  Now you may send notifications!
*/

var Notification = require('node_apns').Notification;

notifier.notify(Notification("######my-token-id#####", { aps: { alert: "Hello from service", sound: "default" }}), 
  function (err) { 
    if (!err) console.log("Sent", this); 
    else console.log('Error', err, 'on', this);
  }
);
```

ah that's true 'm testing in production atm and ######my-token-id##### is replaced with a real value.

inside /certificates/ there are the two cert file (cert&key)

**Comment by matteocrippa** [comment]
I tried to debug services.js and in particular the consume function.
As far as I figured out cansend is set to false using that code and the test case 

``` javascript
    while (cansend && pending.length) {
```

is always false. I tried adding 

``` javascript
    notifier.restart()
```

 at the last line of my source and it started sending pushes, so it seems that _cansend_ needs to be forced somehow to true

**Comment by Orion98MC** [comment]
cansend is set to true right after the startup feedback is complete. There may be an error during the feedback. please check that the feedback works with you pem certificates.

**Comment by Orion98MC** [comment]
Matteo, please re-try with the version in the "dev" branch. Set the notifier verbosity to true and run the code without notifier.restart(). Then give me the output logs.

**Comment by matteocrippa** [comment]
Sry for late reply, I was able to test it with the dev branch.

Starting the test app I received a 10/15 message like these:

+++ Feedback device: ######## 

then it hangs, but not push is being sent to my test device.

if I add notifier.restart() it works fine

**Comment by Orion98MC** [comment]
The feedback reported devices are those Apple could not contact repeatedly. You should not sent these notifications unless you know they are now contactable.

Anyways, you should also see a ""+++ Feedback connection ended!"" or any other "Feedback error..." etc...
The feedback _Must_ be successful for the deliveries to begin. So this is where you should troubleshoot the issue in the first place.

**Comment by matteocrippa** [comment]
Just tested again putting only my device, but nothing happens. It stays stuck on terminal waiting for output something.
The node process is still up and running.
But no response about feedback service.

**Comment by Orion98MC** [comment]
Could you copy/past the console log

**Comment by matteocrippa** [comment]
Here you are

Without restart and dev branch

Matteos-MacBook-Air:mmnapns matteocrippa$ node pushtest.js
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
+++ Feedback device: ----obfuscation----
^C
Matteos-MacBook-Air:mmnapns matteocrippa$

with restart & dev branch

Matteos-MacBook-Air:mmnapns matteocrippa$ node pushtest.js
**\* Consumed 0
development mode
**\* Sent notification 0
Sent { expiry: 0,
  identifier: 0,
  encoding: 'utf8',
  device: { token: '----obfuscation----' },
  payload: { aps: { alert: 'Hello from service', sound: 'default' } },
  alert: undefined,
  badge: undefined,
  sound: undefined,
  callback: [Function] }
**\* Consumed all

**Comment by Orion98MC** [comment]
Ok so the problem definitely comes from the Feedback connexion not being closed or ended.

**Comment by matteocrippa** [comment]
I'll give it a try decreasing the grace period?

**Comment by Orion98MC** [comment]
No, it has nothing to do with the grace period.

Can you check the feedback with this script:

```
var feedback = require('node_apns').Feedback({cert:cert_data, key:key_data});

        feedback.on('device', function(time, token) {
            console.log('Token', token, "is not responding since", new Date(time * 1000));
        });

        feedback.on('end', function () { 
            console.log('Done!'); 
        });
```

You should see a "done" console log when the feedback connection ends. If not then there is a problem.

**Comment by matteocrippa** [comment]
Just tried, the script finish to work but nothing is being put on terminal as response.

**Comment by Orion98MC** [comment]
Is it a development or production certificate you are using ? If you are using a dev cert, then you must change the feedback host, and also set the verbose mode:

```
var host = require('node_apns').APNS.development.host.replace('gateway','feedback');
var feedback = require('node_apns').Feedback({cert:cert_data, key:key_data}, {verbose: true, host:host});
```

This should output a lot more stuff.

**Comment by matteocrippa** [comment]
It's a production one, as you saw before it seems to work because during the previous test it show the response of unreachable devices from AAPL system.

Btw here you are the output:

``` shell
Tue Jul 23 2013 15:43:16 GMT+0200 (CEST) - Feedback from feedback.push.apple.com:2196
Tue Jul 23 2013 15:43:17 GMT+0200 (CEST) - Emit  { '0': 'close' }
```

**Comment by Orion98MC** [comment]
Yes, but previously the services.Notifier was used and automatically set the right host for feedback based on the options you passed at instanciation. Here we do it by hand so we must figure it out.

So the "close" is indeed emitted. Which is great! So now I see why this did not work as expected for you.

Which versions of node/npm do you use by the way ?

**Comment by matteocrippa** [comment]
I'm testing it on two machines:
- node v0.10.9 / npm 1.2.24 (osx)
- node v0.10.13 / npm 1.3.2 (ubuntu) 

on both 'm using the dev branch of npm

**Comment by Orion98MC** [comment]
Ok Matteo, I've updated the dev branch, now you may pull the updates and test with the services.Notifier without restart()

**Comment by matteocrippa** [comment]
Yep, not it works fine, checks for feedbacks and once finished start processing the pushes.
Now it stays stuck on node process once terminated (consumed all), probably we are experiencing the same issue for feedback response even for the pushes?

**Comment by Orion98MC** [comment]
No that's expected behavior. When no more notifications need to be sent, the notifier waits until you submit an other notification. If you wish to exit then you must call suspend() after all notifications have been sent. It much like a database connexion. When you don't need it anymore you must say so.

**Comment by matteocrippa** [comment]
Ah ok! But if I call for suspend and I close the node process I will loose all the feedback blacklist generated by the module? Or it is cached on disk?

**Comment by Orion98MC** [comment]
Nothing is persisted. You have to do it by hand. The service is designed to be run continuously.

**Comment by Orion98MC** [comment]
You may access the black list though (notifier.blacklist) and write the JSON representation to a file.
